# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DcApiEx.Model.GetCollectionById200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :info
  ]

  @type t :: %__MODULE__{
    :data => map() | nil,
    :info => map() | nil
  }

  def decode(value) do
    value
  end
end

