# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DcApiEx.Model.GetAuthToken200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :token,
    :expires
  ]

  @type t :: %__MODULE__{
    :token => String.t | nil,
    :expires => DateTime.t | nil
  }

  alias DcApiEx.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:expires, :datetime, nil)
  end
end

