# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DcApiEx.Model.Info do
  @moduledoc """
  Additional Information
  """

  @derive JSON.Encoder
  defstruct [
    :description,
    :link_expiration,
    :name,
    :version
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :link_expiration => DateTime.t | nil,
    :name => String.t,
    :version => String.t
  }

  alias DcApiEx.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:link_expiration, :datetime, nil)
  end
end

